- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh
    state: present

- name: Oh My Zsh!
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: ~/.oh-my-zsh

- name: Get stats of a .zshrc
  ansible.builtin.stat:
    path: ~/.zshrc
  register: zshrc_stat

- name: Create .zshrc
  ansible.builtin.copy:
    src: ./.oh-my-zsh/templates/zshrc.zsh-template
    dest: ./.zshrc
    remote_src: yes
  when: not zshrc_stat.stat.exists

- name: Powerlevel10k
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Set Theme for Oh My Zsh!
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: ZSH_THEME="powerlevel10k/powerlevel10k"

- name: Add source for powerlevel10k in .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: 'source ~/\.p10k.zsh'
    line: "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"

- name: Copy config for powerlevel10k
  ansible.builtin.copy:
    src: ./.p10k.zsh
    dest: ~/.p10k.zsh

- name: Install highlight for Oh My ZSH
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Install autocomplite for Oh My ZSH
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Turn on plugins for Oh My ZSH
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^plugins='
    line: plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

- name: Change default shell for user
  become: true
  ansible.builtin.user:
    name: std
    shell: /usr/bin/zsh
